# Generated by Django 3.2.5 on 2021-07-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='total')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api_csv.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api_csv.gem')),
            ],
        ),
    ]
